#!/bin/bash

# setup java env
export JAVA_HOME=$SNAP/usr/lib/jvm/java-8-openjdk-$SNAP_ARCH
export PATH=$JAVA_HOME/jre/bin:$PATH

# TODO: split into SNAP_COMMON SNAP_DATA
# copy over data from snap if needed
# conf
if [ ! -d $SNAP_COMMON/conf ]; then
    cp -rf $SNAP/conf $SNAP_COMMON/
fi

# userdata
if [ ! -d $SNAP_COMMON/userdata ]; then
    cp -rf $SNAP/userdata $SNAP_COMMON/
fi

# runtime
mkdir -p $SNAP_COMMON/karaf
# TODO: this probably should be $SNAP_COMMON
if [ ! -d $SNAP_COMMON/karaf/etc ]; then
    cp -rf $SNAP/runtime/karaf/etc $SNAP_COMMON/karaf/
fi


DIRNAME=$SNAP
exec "${DIRNAME}/runtime/karaf/bin/karaf" "${@}"

