name: openhab
version: "2.0.0.b4-7"
summary: openhab 2.0 smart home server
description: |
 openHAB - a vendor and technology agnostic open source automation software for your home.
 webgui is available at user defined port(default is 8080 for http and 8443 for https)
 http://<snap device address>:{specified http port}
 https:///<snap device address>:{specified https port}
 Port settings can be altered by calling:
 $ snap set openhab OPENHAB_HTTP_PORT="<port value>"
 $ snap set openhab OPENHAB_HTTPS_PORT="<port value>"
 to make port change effective, service needs to be restarted:
 $ sudo systemctl restart snap.openhab.openhab.service

confinement: strict
grade: stable

apps:
    openhab:
        command: openhab-control karaf server
        stop-command: openhab-control stop
        daemon: simple
        plugs: [home, network, network-bind, serial-port]

    start:
        command: openhab-control karaf
        plugs: [home, network, network-bind]

    clean:
        command: openhab-control karaf clean
        plugs: [home, network, network-bind]

    debug:
        command: openhab-control karaf debug
        plugs: [home, network, network-bind]

    status:
        command: openhab-control status
        plugs: [home, network, network-bind]

    stop:
        command: openhab-control stop
        plugs: [home, network, network-bind]

    console:
        command: openhab-control shell
        plugs: [home, network, network-bind, process-control]

    client:
        command: openhab-control client
        plugs: [home, network, network-bind]

    help:
        command: openhab-help

parts:
    openhab:
        source: https://bintray.com/openhab/mvn/download_file?file_path=org%2Fopenhab%2Fdistro%2Fopenhab-online%2F2.0.0.b4%2Fopenhab-online-2.0.0.b4.tar.gz
        plugin: openhab
        stage:
          - -start*
          - -runtime/bin/*.bat
        snap:
          - -start*
          - -runtime/bin/*.bat

    # java run time
    jre:
        plugin: custom-jre
        zulu:
            armhf: http://cdn.azul.com/zulu-embedded/bin/ezdk-1.8.0_102-8.17.0.21-eval-linux_aarch32hf.tar.gz
            # armel:
            # arm64:
            amd64: http://cdn.azul.com/zulu/bin/zulu8.19.0.1-jdk8.0.112-linux_x64.tar.gz
            # i386:

    # helper scripts
    openhab-control:
        source: src
        plugin: dump
        organize:
            openhab-control: bin/openhab-control
            connect-interfaces: bin/connect-interfaces
            config: bin/config
            openhab-help: bin/openhab-help
            configure: meta/hooks/configure
