#!/bin/bash

echo "This is helper script and it shoud be called by user directly!"
echo "Connecting interfaces for openhab"

snap connect openhab:home ubuntu-core:home
snap connect openhab:process-control ubuntu-core:process-control
