#!/bin/bash

# read settings if available
# TODO: uncomment folling, once snapctl can be called from outside the hooks
# list of supported keys
# keys=("OPENHAB_HTTP_PORT" "OPENHAB_HTTPS_PORT")
# for key in ${keys[@]}
# do
#   if value=$(snapctl get $key); then
#       echo "$key='$value'"
#       export $key=$value
#   fi
# done
# TODO: get rid of this workaround once above can be used
if [ -f $SNAP_COMMON/openhab_settings.sh ]; then
    source $SNAP_COMMON/openhab_settings.sh
fi

# TODO: split into SNAP_COMMON SNAP_DATA
# copy over data from snap if needed
# conf
if [ ! -d $SNAP_COMMON/conf ]; then
    cp -rf $SNAP/conf $SNAP_COMMON/
fi

# userdata
if [ ! -d $SNAP_COMMON/userdata ]; then
    cp -rf $SNAP/userdata $SNAP_COMMON/
fi

# runtime
mkdir -p $SNAP_COMMON/karaf
# TODO: this probably should be $SNAP_COMMON
if [ ! -d $SNAP_COMMON/karaf/etc ]; then
    cp -rf $SNAP/runtime/karaf/etc $SNAP_COMMON/karaf/
fi

DIRNAME=$SNAP
exec "${DIRNAME}/runtime/karaf/bin/karaf" "${@}"
