#!/bin/bash

# read openhab config
source $SNAP/bin/config

# read settings if available
# TODO: uncomment folling, once snapctl can be called from outside the hooks
# list of supported keys
# keys=("OPENHAB_HTTP_PORT" "OPENHAB_HTTPS_PORT")
# for key in ${keys[@]}
# do
#   if value=$(snapctl get $key); then
#       echo "$key='$value'"
#       export $key=$value
#   fi
# done

# TODO: get rid of this workaround once above can be used
# loop through all values, and if not defined, use default value
for key in ${keys[@]}
do
  if [ -z "${!key}" ]; then
      # use default value
      default_value="DEFAULT_$key"
      echo "using default value: $key='${!default_value}'"
      export $key=${!default_value}
      # echo "export $key='${!def_value}'" >> $SETTINGS_FILE
  else
      echo "$key='${!key}'"
  fi
done

# copy over data from snap if needed
# conf
if [ ! -d $SNAP_COMMON/conf ]; then
    cp -rf $SNAP/conf $SNAP_COMMON/
fi

# userdata
if [ ! -d $SNAP_COMMON/userdata ]; then
    cp -rf $SNAP/userdata $SNAP_COMMON/
fi

# runtime
mkdir -p $SNAP_COMMON/karaf
# TODO: this probably should be $SNAP_COMMON
if [ ! -d $SNAP_COMMON/karaf/etc ]; then
    cp -rf $SNAP/runtime/karaf/etc $SNAP_COMMON/karaf/
fi

DIRNAME=$SNAP
exec "${DIRNAME}/runtime/karaf/bin/karaf" "${@}"
