#!/bin/bash

# setup java env, jre can be in different locations
# as we might use openjdk on x86 and zulu on armhf
if [ -d $SNAP/jre ]; then
    export JAVA_HOME=$SNAP/jre
    export PATH=$JAVA_HOME/bin:$PATH
else
    export JAVA_HOME=$SNAP/usr/lib/jvm/java-8-openjdk-$SNAP_ARCH
    export PATH=$JAVA_HOME/jre/bin:$PATH
fi

# read settings if available
# TODO: uncomment folling, once snapctl can be called from outside the hooks
# if pvalue=$(snapctl get OPENHAB_HTTPS_PORT); then
#     OPENHAB_HTTPS_PORT=$pvalue
# fi
#
# if pvalue=$(snapctl get OPENHAB_HTTP_PORT); then
#     OPENHAB_HTTP_PORT=$pvalue
# fi
# TODO: get rid of this workaround once above can be used
source $SNAP_COMMON/openhab_settings.sh

# TODO: split into SNAP_COMMON SNAP_DATA
# copy over data from snap if needed
# conf
if [ ! -d $SNAP_COMMON/conf ]; then
    cp -rf $SNAP/conf $SNAP_COMMON/
fi

# userdata
if [ ! -d $SNAP_COMMON/userdata ]; then
    cp -rf $SNAP/userdata $SNAP_COMMON/
fi

# runtime
mkdir -p $SNAP_COMMON/karaf
# TODO: this probably should be $SNAP_COMMON
if [ ! -d $SNAP_COMMON/karaf/etc ]; then
    cp -rf $SNAP/runtime/karaf/etc $SNAP_COMMON/karaf/
fi

DIRNAME=$SNAP
exec "${DIRNAME}/runtime/karaf/bin/karaf" "${@}"
